name: Update Personal Medicine Counter

on:
  schedule:
    - cron: '0 13 * * *'  
    - cron: '0 1 * * *'  
  workflow_dispatch:  

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Autenticar com o Google Cloud
        uses: google-github-actions/auth@v1
        with: 
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Execute script
        run: |
          python src/update_medicine.py
